build: improve compatibility with .Net 4.6.1 and Netstandard 2.0
AxaGuilDEv/extensions-dependency-injection pull request #12
Opened 2021-01-26 10:53 UTC by remija

# Pull Request Template

## PR Checklist

- [ ] I have run `<TEST COMMAND>` locally and all tests are passing.
- [ ] I have added/updated tests for any new behavior.
- [ ] If this is a significant change, an issue has already been created where the problem / solution was discussed: [N/A, or add link to issue here]

## PR Description

Improve compatibility with .Net 4.6.1 and Netstandard 2.0 about Dependency Injection librairies version

2021-01-26 11:02 UTC, JLou commented
Ca serait possible de ne pas toucher au whitespaces des cspprojs ? Ca pollue la PR le passage de 2 espaces à 4 espaces d'indentation

2021-01-26 13:28 UTC, remija commented
> Ca serait possible de ne pas toucher au whitespaces des cspprojs ? Ca pollue la PR le passage de 2 espaces à 4 espaces d'indentation

Voilà j'ai corrigé le fichier impacté

2021-01-26 15:35 UTC, JLou commented
Regarde bien la PR, on a encore des fichiers xml ou seul whitespace est modifié sur certaines lignes. Essaie de corriger stp

2021-01-27 07:50 UTC, remija commented
> Regarde bien la PR, on a encore des fichiers xml ou seul whitespace est modifié sur certaines lignes. Essaie de corriger stp

Ok, je n'avais pas fait attention, c'est réglé normalement !

2021-01-27 11:19 UTC, JLou commented
C'est bon pour moi !
Ca serait cool que @g7ed6e jette un oeil

2021-01-27 18:35 UTC, g7ed6e requested changes
Afaik these packages will always be installed in .net full framework hosts. I would drop netstandard 2.0 support.

2021-01-28 15:25 UTC, remija commented
> Afaik these packages will always be installed in .net full framework hosts. I would drop netstandard 2.0 support.

OK Guillaume, j'ai fait le nécessaire.

2021-01-28 15:57 UTC, JLou approved these changes

2021-01-28 19:20 UTC, g7ed6e approved these changes

2021-01-29 14:08 UTC, merged